// Runtime configuration for the BookPilot AI backend.
//
// Every secret is read here and nowhere else, so there is exactly one
// place to audit for "does this value ever reach the browser?". The
// answer is no: nothing in this module is serialised into a response.
//
// Netlify exposes env vars through both `Netlify.env` and `process.env`
// depending on the runtime; read whichever is present.

function read(name) {
  try {
    if (typeof Netlify !== "undefined" && Netlify.env) {
      const v = Netlify.env.get(name);
      if (v) return v;
    }
  } catch {
    /* Netlify global not available (local node, tests) */
  }
  if (typeof process !== "undefined" && process.env && process.env[name]) {
    return process.env[name];
  }
  return "";
}

export const env = {
  // --- Supabase -------------------------------------------------------
  supabaseUrl: read("SUPABASE_URL"),
  supabaseAnonKey: read("SUPABASE_ANON_KEY"),
  // Service role bypasses RLS. Used only for the operations listed in
  // bookpilot/README.md § "Where the service role is used".
  supabaseServiceKey: read("SUPABASE_SERVICE_ROLE_KEY"),

  // --- Anthropic ------------------------------------------------------
  anthropicKey: read("ANTHROPIC_API_KEY"),
  // Netlify's AI Gateway injects ANTHROPIC_API_KEY and ANTHROPIC_BASE_URL
  // into the function environment, and its values win over site ones.
  // Honouring the base URL is what makes that pairing work; without it
  // the gateway's token goes to api.anthropic.com, which rejects it.
  anthropicBaseUrl: read("ANTHROPIC_BASE_URL"),

  // --- Stripe ---------------------------------------------------------
  stripeSecret: read("STRIPE_SECRET_KEY"),
  stripeWebhookSecret: read("STRIPE_WEBHOOK_SECRET"),

  // --- Meta Marketing API ---------------------------------------------
  metaAppId: read("META_APP_ID"),
  metaAppSecret: read("META_APP_SECRET"),
  metaRedirectUri: read("META_REDIRECT_URI"),
  // --- Pinterest Ads API (read-only) ------------------------------------
  pinterestAppId: read("PINTEREST_APP_ID"),
  pinterestAppSecret: read("PINTEREST_APP_SECRET"),
  pinterestRedirectUri: read("PINTEREST_REDIRECT_URI"),
  // --- TikTok Marketing API (read-only) ----------------------------------
  tiktokAppId: read("TIKTOK_APP_ID"),
  tiktokAppSecret: read("TIKTOK_APP_SECRET"),
  // The "Advertiser authorization URL" shown for the app in the TikTok
  // developer portal (My Apps > the app > Basic Information). It carries the
  // app id and the redirect address; only `state` is set at run time.
  tiktokAuthUrl: read("TIKTOK_AUTH_URL"),
  // --- Google Ads API (reads only) ---------------------------------------
  // An OAuth client (Google Cloud) plus a developer token approved for
  // production. Not to be confused with "Sign in with Google", which is
  // configured on the Supabase project.
  googleAdsClientId: read("GOOGLE_ADS_CLIENT_ID"),
  googleAdsClientSecret: read("GOOGLE_ADS_CLIENT_SECRET"),
  googleAdsDeveloperToken: read("GOOGLE_ADS_DEVELOPER_TOKEN"),
  googleAdsRedirectUri: read("GOOGLE_ADS_REDIRECT_URI"),
  // --- Amazon Ads API: Amazon Attribution (reads only) ---------------------
  // A Login with Amazon security profile whose client has been granted
  // Amazon Ads API access. There is no separate developer token.
  amazonAdsClientId: read("AMAZON_ADS_CLIENT_ID"),
  amazonAdsClientSecret: read("AMAZON_ADS_CLIENT_SECRET"),
  amazonAdsRedirectUri: read("AMAZON_ADS_REDIRECT_URI"),
  // Random string used to sign the OAuth `state` parameter (CSRF guard).
  oauthStateSecret: read("BOOKPILOT_OAUTH_STATE_SECRET"),

  // --- Deployment -----------------------------------------------------
  siteUrl: read("BOOKPILOT_SITE_URL") || read("URL") || "http://localhost:8888",
  allowedOrigins: (read("BOOKPILOT_ALLOWED_ORIGINS") || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
};

// Which capabilities the server can actually deliver right now. The
// client asks for this (via /api/bp/config) and renders "Connect
// integration" or "Demo mode" for anything that is off, instead of
// showing a control that would fail (spec §55).
export function capabilities() {
  return {
    database: Boolean(env.supabaseUrl && env.supabaseAnonKey),
    ai: Boolean(env.anthropicKey),
    billing: Boolean(env.stripeSecret),
    meta: Boolean(env.metaAppId && env.metaAppSecret && env.metaRedirectUri),
    pinterest: Boolean(env.pinterestAppId && env.pinterestAppSecret && env.pinterestRedirectUri),
    tiktok: Boolean(env.tiktokAppId && env.tiktokAppSecret && env.tiktokAuthUrl),
    google: Boolean(env.googleAdsClientId && env.googleAdsClientSecret && env.googleAdsDeveloperToken && env.googleAdsRedirectUri),
    amazon: Boolean(env.amazonAdsClientId && env.amazonAdsClientSecret && env.amazonAdsRedirectUri),
    // Image and video rendering need a media provider that is not wired
    // up yet. Concepts and prompts are generated by the text model; the
    // rendering step is explicitly unavailable rather than faked.
    imageGeneration: false,
    videoGeneration: false,
  };
}

export function requireEnv(...names) {
  const missing = names.filter((n) => !env[n]);
  if (missing.length) {
    const err = new Error(`Missing server configuration: ${missing.join(", ")}`);
    err.code = "server_misconfigured";
    throw err;
  }
}
