// Mockups.
//
// Studio-lit product shots of the author's own book — an open hardcover,
// a softcover beside its cover, a standing copy, a stack, a trio — made
// from the real cover and the real laid-out pages. They exist for the
// sales page, the retailer listing and the ads BookPilot builds next.
//
// These are renders of the file, not photographs of a printed copy, and
// the screen says so. Nothing is generated by a model and nothing costs
// a credit.

import { html, raw, delegate } from "../../core/dom.js";
import { BB, saveFile } from "../../core/builder-api.js";
import { notify } from "../../core/toast.js";
import { projectHeader } from "./shared.js";
import { demoBadge } from "../shared.js";
import { trimSize } from "../../doc/themes.js";
import { layoutBook } from "../../doc/layout.js";
import { assembleBook } from "../../doc/assemble.js";
import { safeUrl } from "../../core/dom.js";
import { PALETTES, SCENES, paletteById, prepareAssets, renderScene } from "./mockup-engine.js";

const THUMB_WIDTH = 1000;
const EXPORT_WIDTH = 2400;
const PALETTE_KEY = "bookpilot.mockup.palette";

function rememberedPalette() {
  try { return paletteById(localStorage.getItem(PALETTE_KEY)).id; } catch { return PALETTES[0].id; }
}

function loadImage(url) {
  return new Promise((resolve) => {
    if (!url) return resolve(null);
    const img = new Image();
    // Anonymous, so a cross-origin cover that allows it does not taint
    // the canvas; one that does not simply renders without the picture.
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

async function loadFonts() {
  if (!document.fonts?.load) return;
  await Promise.all([
    document.fonts.load("400 28px 'DM Serif Display'"),
    document.fonts.load("600 28px 'DM Sans'"),
  ]).catch(() => {});
}

/** Pairs of facing pages, verso on the left, the way a book opens. */
function spreadsOf(laid) {
  if (!laid) return [];
  const out = [];
  for (let i = 1; i < laid.pages.length; i += 2) {
    const left = laid.pages[i], right = laid.pages[i + 1];
    if (!left && !right) continue;
    out.push({
      index: i,
      left,
      right,
      label: `Pages ${left?.folio || i + 1}${right ? `–${right.folio || i + 2}` : ""}`,
      hasText: Boolean(left?.items?.length || right?.items?.length),
    });
  }
  return out;
}

function defaultSpread(spreads, laid) {
  if (!spreads.length) return 0;
  const from = laid?.frontCount || 0;
  // The first spread past the front matter that actually has text.
  const found = spreads.findIndex((s) => s.index >= from + 1 && s.hasText);
  return found === -1 ? 0 : found;
}

export async function render(container, params) {
  const [full, manuscript] = await Promise.all([
    BB.project(params.id),
    BB.manuscript(params.id).catch(() => null),
  ]);
  const { project, covers = [] } = full;
  const trim = trimSize(project.trim_size);

  let laid = null;
  if (manuscript) {
    try {
      const book = assembleBook(manuscript);
      if (book.sections.length) laid = layoutBook(book, { print: false });
    } catch (err) {
      console.error("[bookpilot] mockups: layout failed, using blank pages:", err);
    }
  }
  const spreads = spreadsOf(laid);

  const state = {
    palette: rememberedPalette(),
    spread: defaultSpread(spreads, laid),
    cover: (covers.find((c) => c.is_selected) || covers[0] || null)?.id || null,
    token: 0,
    assets: null,
  };
  const coverById = (id) => covers.find((c) => c.id === id) || null;

  container.innerHTML = html`
    ${raw(projectHeader(project, { active: "mockups", actions: demoBadge() }))}

    <div class="bb-stage">
      <div class="bb-mock-head">
        <div>
          <h2 class="bb-section-title" style="margin:0">Mockups</h2>
          <p class="bp-small bp-muted" style="margin:4px 0 0;max-width:62ch">
            Studio shots built from your actual cover and your actual pages. Pick a backdrop,
            pick the spread to show, download what you like. Free — no credits.
          </p>
        </div>
      </div>

      <div class="bb-mock-controls">
        <div class="bb-mock-control">
          <span class="bb-mock-label" id="mock-palette-label">Backdrop</span>
          <div class="bb-mock-palettes" role="radiogroup" aria-labelledby="mock-palette-label">
            ${raw(PALETTES.map((p) => html`
              <button type="button" class="bb-mock-palette" role="radio" data-action="palette" data-id="${p.id}"
                      aria-checked="${p.id === state.palette}" title="${p.name}">
                <span class="bb-mock-swatch" style="background:linear-gradient(135deg,${p.swatch[0]} 0 55%,${p.swatch[1]} 55% 100%)"></span>
                <span class="bb-mock-palette__name">${p.name}</span>
              </button>`).join(""))}
          </div>
        </div>

        <div class="bb-mock-selects">
          ${covers.length > 1 ? raw(html`
            <label class="bb-mock-control">
              <span class="bb-mock-label">Cover</span>
              <select class="bp-select" data-change="cover">
                ${raw(covers.map((c, i) => html`<option value="${c.id}" ${c.id === state.cover ? "selected" : ""}>
                  ${c.is_selected ? "★ " : ""}${c.concept_name || c.name || `Concept ${i + 1}`}</option>`).join(""))}
              </select>
            </label>`) : ""}
          ${spreads.length ? raw(html`
            <label class="bb-mock-control">
              <span class="bb-mock-label">Spread</span>
              <select class="bp-select" data-change="spread">
                ${raw(spreads.map((s, i) => html`<option value="${i}" ${i === state.spread ? "selected" : ""}>${s.label}</option>`).join(""))}
              </select>
            </label>`) : ""}
        </div>
      </div>

      ${!covers.length ? raw(html`
        <div class="bp-alert bp-alert--info" style="margin-bottom:var(--bp-5)">
          <span class="bp-alert__icon">i</span>
          <div>No cover yet, so these use a placeholder set from your title.
            <a href="#/studio/${project.id}/cover">Choose a cover</a> and they update.</div>
        </div>`) : ""}
      ${!spreads.length ? raw(html`
        <div class="bp-alert bp-alert--info" style="margin-bottom:var(--bp-5)">
          <span class="bp-alert__icon">i</span>
          <div>No pages to show yet, so open books show blank paper.
            <a href="#/studio/${project.id}/write">Write a chapter</a> and they fill in.</div>
        </div>`) : ""}

      <div class="bb-mock-grid" id="mock-grid">
        ${raw(SCENES.map((scene) => html`
          <figure class="bb-mock-card" data-scene="${scene.id}">
            <div class="bb-mock-frame"><canvas width="${THUMB_WIDTH}" height="${Math.round(THUMB_WIDTH * 2 / 3)}"
              role="img" aria-label="${scene.name} mockup of ${project.title || "your book"}"></canvas></div>
            <figcaption class="bb-mock-caption">
              <div>
                <div class="bb-mock-name">${scene.name}</div>
                <div class="bp-tiny bp-subtle">${scene.blurb}</div>
              </div>
              <button type="button" class="bp-btn bp-btn--secondary bp-btn--sm" data-action="download" data-scene="${scene.id}">PNG</button>
            </figcaption>
          </figure>`).join(""))}
      </div>

      <p class="bp-tiny bp-subtle" style="margin-top:var(--bp-5);max-width:70ch">
        These are renders of your file, not photographs of a printed copy. Page thickness is
        estimated from the page count; the real spine depends on your printer's paper.
      </p>
    </div>
  `;

  const grid = container.querySelector("#mock-grid");

  async function buildAssets() {
    const cover = coverById(state.cover);
    const spread = spreads[state.spread] || {};
    const image = await loadImage(safeUrl(cover?.image_url) || "");
    state.assets = prepareAssets({
      cover,
      project,
      trim,
      pageCount: laid?.pages?.length || Math.max(24, project.progress?.estimatedPages || 120),
      pageLeft: spread.left || null,
      pageRight: spread.right || null,
      image,
    });
  }

  async function paintAll() {
    const token = ++state.token;
    await loadFonts();
    await buildAssets();
    for (const scene of SCENES) {
      if (token !== state.token) return; // a newer choice supersedes this one
      const card = grid.querySelector(`[data-scene="${scene.id}"] canvas`);
      if (!card) return;
      try {
        const out = renderScene(scene.id, state.palette, state.assets, { width: THUMB_WIDTH });
        const ctx = card.getContext("2d");
        ctx.clearRect(0, 0, card.width, card.height);
        ctx.drawImage(out, 0, 0, card.width, card.height);
      } catch (err) {
        console.error(`[bookpilot] mockup ${scene.id} failed:`, err);
      }
      // Yield between scenes so the page stays responsive while six
      // renders come up.
      await new Promise((r) => setTimeout(r, 0));
    }
  }

  delegate(container, "click", {
    palette(trigger) {
      state.palette = trigger.dataset.id;
      try { localStorage.setItem(PALETTE_KEY, state.palette); } catch { /* private mode */ }
      container.querySelectorAll('[data-action="palette"]').forEach((b) =>
        b.setAttribute("aria-checked", String(b.dataset.id === state.palette)));
      paintAll();
    },
    async download(trigger) {
      const sceneId = trigger.dataset.scene;
      const scene = SCENES.find((s) => s.id === sceneId);
      trigger.disabled = true;
      try {
        await loadFonts();
        if (!state.assets) await buildAssets();
        const canvas = renderScene(sceneId, state.palette, state.assets, { width: EXPORT_WIDTH });
        const blob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));
        if (!blob) throw new Error("The browser could not encode the image.");
        const slug = String(project.title || "book").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "book";
        saveFile(blob, `${slug}-${sceneId}-${state.palette}.png`);
        notify.success(`${scene?.name || "Mockup"} saved.`);
      } catch (err) {
        console.error("[bookpilot] mockup export failed:", err);
        notify.error("That mockup could not be exported. If your cover uses an image hosted elsewhere, upload it to BookPilot first.");
      } finally {
        trigger.disabled = false;
      }
    },
  });

  container.addEventListener("change", (event) => {
    const which = event.target?.dataset?.change;
    if (which === "cover") state.cover = event.target.value;
    else if (which === "spread") state.spread = Number(event.target.value) || 0;
    else return;
    paintAll();
  });

  paintAll();
}
